version: '3.8'

services:
  liquidity-pools-mcp:
    image: liquidity-pools-mcp:latest
    container_name: liquidity-pools-mcp
    ports:
      - "8000:8000"
    environment:
      - FASTMCP_HOST=0.0.0.0
      - FASTMCP_PORT=8000
      - FASTMCP_DEBUG=false
      - FASTMCP_LOG_LEVEL=INFO
    deploy:
      replicas: 1
      restart_policy:
        condition: unless-stopped
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -s -o /dev/null -w '%{http_code}' http://localhost:8000/ | grep -qv '000' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: overlay
    attachable: true